version: '3'

services:
  app:
    build: .
    ports:
      - '8080:8080'
    container_name: links_application
    environment:
      POSTRGES_DBNAME: 'postgres'
      STORAGE_MODE: 'postgres'
      DATABASE_URL: 'postgres://postgres:postgres@localhost:5432/postgres'
    tty: true
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postrges
      - POSTGRES_PASSWORD=postrges
      - POSTGRES_DB=postrges
    volumes:
      - './_sql/:/docker-entrypoint-initdb.d/'
    tty: true
#
#  cache:
#    image: redis:latest
#    ports:
#      - 6739:6739