version: '3'

services:
  app:
    build: .

    ports:
      - '6060:6060'
    container_name: links_application
    environment:
      POSTRGES_DBNAME: 'postgres'
      STORAGE_MODE: 'postgres'
#      DATABASE_URL: 'postgres://postgres:5432/postgres'
    depends_on:
      - database

  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    user: postgres
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'linksdb'
    volumes:
      - './_sql/:/docker-entrypoint-initdb.d/'



#
#  cache:
#    image: redis:latest
#    ports:
#      - 6739:6739